name: Service Directory
services:
  mssql:
    container_name: Service-Directory
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: QbLJzwGblAR3USLi
      ACCEPT_EULA: Y
    restart: no
    volumes:
      - sql:/var/opt/mssql
volumes:
  sql:
    name: Service-Directory