name: Service-Directory
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: QbLJzwGblAR3USLi
      ACCEPT_EULA: Y
    restart: no
    volumes:
      - ./sql/data:/var/opt/mssql/data
      - ./sql/log:/var/opt/mssql/log
      - ./sql/secrets:/var/opt/mssql/secrets
      - ./sql/backup:/var/opt/mssql/backup