version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
    groups:
      github-actions-development:
        patterns:
          - '*'

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nuget:
        patterns:
          - '*'
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "development"
    groups:
      nuget-development:
        patterns:
          - '*'

  - package-ecosystem: "npm"
    directory: "/src/ServiceDirectory.Presentation.Web.Node"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: "npm"
    directory: "/src/ServiceDirectory.Presentation.Web.Node"
    schedule:
      interval: "daily"
    target-branch: "development"
    groups:
      npm-development:
        patterns:
          - '*'